/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mono (https://sketchfab.com/michela.000)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/charlize-theron-head-ca8926f4284045c6a2e75a6f7642c851
title: CHARLIZE THERON_HEAD
*/

import React, { useRef, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();

  // useLayoutEffect(() => {
  //   group.current.translate(0, -10, 0);
  // }, []);

  const { nodes, materials } = useGLTF("/head.gltf");
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={0.1}
      position={[0, -1, 0]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Default_OBJ}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/head.gltf");
